lib: [
  "_build/install/default/lib/pixlang/META"
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser.cmi" {"__private__/analyser/.public_cmi/analyser.cmi"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser.cmt" {"__private__/analyser/.public_cmi/analyser.cmt"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser.cmti" {"__private__/analyser/.public_cmi/analyser.cmti"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser__.cmi" {"__private__/analyser/.public_cmi/analyser__.cmi"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser__.cmt" {"__private__/analyser/.public_cmi/analyser__.cmt"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser__Renaming.cmi" {"__private__/analyser/.public_cmi/analyser__Renaming.cmi"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser__Renaming.cmt" {"__private__/analyser/.public_cmi/analyser__Renaming.cmt"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser__Simplifier.cmi" {"__private__/analyser/.public_cmi/analyser__Simplifier.cmi"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser__Simplifier.cmt" {"__private__/analyser/.public_cmi/analyser__Simplifier.cmt"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser__Type_analyser.cmi" {"__private__/analyser/.public_cmi/analyser__Type_analyser.cmi"}
  "_build/install/default/lib/pixlang/__private__/analyser/.public_cmi/analyser__Type_analyser.cmt" {"__private__/analyser/.public_cmi/analyser__Type_analyser.cmt"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser.a" {"__private__/analyser/analyser.a"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser.cma" {"__private__/analyser/analyser.cma"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser.cmx" {"__private__/analyser/analyser.cmx"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser.cmxa" {"__private__/analyser/analyser.cmxa"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser.ml" {"__private__/analyser/analyser.ml"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser.mli" {"__private__/analyser/analyser.mli"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser__.cmx" {"__private__/analyser/analyser__.cmx"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser__.ml" {"__private__/analyser/analyser__.ml"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser__Renaming.cmx" {"__private__/analyser/analyser__Renaming.cmx"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser__Simplifier.cmx" {"__private__/analyser/analyser__Simplifier.cmx"}
  "_build/install/default/lib/pixlang/__private__/analyser/analyser__Type_analyser.cmx" {"__private__/analyser/analyser__Type_analyser.cmx"}
  "_build/install/default/lib/pixlang/__private__/analyser/renaming.ml" {"__private__/analyser/renaming.ml"}
  "_build/install/default/lib/pixlang/__private__/analyser/simplifier.ml" {"__private__/analyser/simplifier.ml"}
  "_build/install/default/lib/pixlang/__private__/analyser/type_analyser.ml" {"__private__/analyser/type_analyser.ml"}
  "_build/install/default/lib/pixlang/__private__/ast/.public_cmi/ast.cmi" {"__private__/ast/.public_cmi/ast.cmi"}
  "_build/install/default/lib/pixlang/__private__/ast/.public_cmi/ast.cmt" {"__private__/ast/.public_cmi/ast.cmt"}
  "_build/install/default/lib/pixlang/__private__/ast/.public_cmi/ast.cmti" {"__private__/ast/.public_cmi/ast.cmti"}
  "_build/install/default/lib/pixlang/__private__/ast/ast.a" {"__private__/ast/ast.a"}
  "_build/install/default/lib/pixlang/__private__/ast/ast.cma" {"__private__/ast/ast.cma"}
  "_build/install/default/lib/pixlang/__private__/ast/ast.cmx" {"__private__/ast/ast.cmx"}
  "_build/install/default/lib/pixlang/__private__/ast/ast.cmxa" {"__private__/ast/ast.cmxa"}
  "_build/install/default/lib/pixlang/__private__/ast/ast.ml" {"__private__/ast/ast.ml"}
  "_build/install/default/lib/pixlang/__private__/ast/ast.mli" {"__private__/ast/ast.mli"}
  "_build/install/default/lib/pixlang/__private__/interpreter/.public_cmi/interpreter.cmi" {"__private__/interpreter/.public_cmi/interpreter.cmi"}
  "_build/install/default/lib/pixlang/__private__/interpreter/.public_cmi/interpreter.cmt" {"__private__/interpreter/.public_cmi/interpreter.cmt"}
  "_build/install/default/lib/pixlang/__private__/interpreter/.public_cmi/interpreter.cmti" {"__private__/interpreter/.public_cmi/interpreter.cmti"}
  "_build/install/default/lib/pixlang/__private__/interpreter/interpreter.a" {"__private__/interpreter/interpreter.a"}
  "_build/install/default/lib/pixlang/__private__/interpreter/interpreter.cma" {"__private__/interpreter/interpreter.cma"}
  "_build/install/default/lib/pixlang/__private__/interpreter/interpreter.cmx" {"__private__/interpreter/interpreter.cmx"}
  "_build/install/default/lib/pixlang/__private__/interpreter/interpreter.cmxa" {"__private__/interpreter/interpreter.cmxa"}
  "_build/install/default/lib/pixlang/__private__/interpreter/interpreter.ml" {"__private__/interpreter/interpreter.ml"}
  "_build/install/default/lib/pixlang/__private__/interpreter/interpreter.mli" {"__private__/interpreter/interpreter.mli"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser.cmi" {"__private__/language_parser/.public_cmi/language_parser.cmi"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser.cmt" {"__private__/language_parser/.public_cmi/language_parser.cmt"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser__Cmly.cmi" {"__private__/language_parser/.public_cmi/language_parser__Cmly.cmi"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser__Cmly.cmt" {"__private__/language_parser/.public_cmi/language_parser__Cmly.cmt"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser__Lexer.cmi" {"__private__/language_parser/.public_cmi/language_parser__Lexer.cmi"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser__Lexer.cmt" {"__private__/language_parser/.public_cmi/language_parser__Lexer.cmt"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser__Parser.cmi" {"__private__/language_parser/.public_cmi/language_parser__Parser.cmi"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser__Parser.cmt" {"__private__/language_parser/.public_cmi/language_parser__Parser.cmt"}
  "_build/install/default/lib/pixlang/__private__/language_parser/.public_cmi/language_parser__Parser.cmti" {"__private__/language_parser/.public_cmi/language_parser__Parser.cmti"}
  "_build/install/default/lib/pixlang/__private__/language_parser/Cmly.ml" {"__private__/language_parser/Cmly.ml"}
  "_build/install/default/lib/pixlang/__private__/language_parser/Lexer.ml" {"__private__/language_parser/Lexer.ml"}
  "_build/install/default/lib/pixlang/__private__/language_parser/Parser.ml" {"__private__/language_parser/Parser.ml"}
  "_build/install/default/lib/pixlang/__private__/language_parser/Parser.mli" {"__private__/language_parser/Parser.mli"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser.a" {"__private__/language_parser/language_parser.a"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser.cma" {"__private__/language_parser/language_parser.cma"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser.cmx" {"__private__/language_parser/language_parser.cmx"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser.cmxa" {"__private__/language_parser/language_parser.cmxa"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser.ml" {"__private__/language_parser/language_parser.ml"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser__Cmly.cmx" {"__private__/language_parser/language_parser__Cmly.cmx"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser__Lexer.cmx" {"__private__/language_parser/language_parser__Lexer.cmx"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser__Parser.cmx" {"__private__/language_parser/language_parser__Parser.cmx"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util.cmi" {"__private__/util/.public_cmi/util.cmi"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util.cmt" {"__private__/util/.public_cmi/util.cmt"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Environment.cmi" {"__private__/util/.public_cmi/util__Environment.cmi"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Environment.cmt" {"__private__/util/.public_cmi/util__Environment.cmt"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Environment.cmti" {"__private__/util/.public_cmi/util__Environment.cmti"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Error_report.cmi" {"__private__/util/.public_cmi/util__Error_report.cmi"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Error_report.cmt" {"__private__/util/.public_cmi/util__Error_report.cmt"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Error_report.cmti" {"__private__/util/.public_cmi/util__Error_report.cmti"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Position.cmi" {"__private__/util/.public_cmi/util__Position.cmi"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Position.cmt" {"__private__/util/.public_cmi/util__Position.cmt"}
  "_build/install/default/lib/pixlang/__private__/util/.public_cmi/util__Position.cmti" {"__private__/util/.public_cmi/util__Position.cmti"}
  "_build/install/default/lib/pixlang/__private__/util/environment.ml" {"__private__/util/environment.ml"}
  "_build/install/default/lib/pixlang/__private__/util/environment.mli" {"__private__/util/environment.mli"}
  "_build/install/default/lib/pixlang/__private__/util/error_report.ml" {"__private__/util/error_report.ml"}
  "_build/install/default/lib/pixlang/__private__/util/error_report.mli" {"__private__/util/error_report.mli"}
  "_build/install/default/lib/pixlang/__private__/util/position.ml" {"__private__/util/position.ml"}
  "_build/install/default/lib/pixlang/__private__/util/position.mli" {"__private__/util/position.mli"}
  "_build/install/default/lib/pixlang/__private__/util/util.a" {"__private__/util/util.a"}
  "_build/install/default/lib/pixlang/__private__/util/util.cma" {"__private__/util/util.cma"}
  "_build/install/default/lib/pixlang/__private__/util/util.cmx" {"__private__/util/util.cmx"}
  "_build/install/default/lib/pixlang/__private__/util/util.cmxa" {"__private__/util/util.cmxa"}
  "_build/install/default/lib/pixlang/__private__/util/util.ml" {"__private__/util/util.ml"}
  "_build/install/default/lib/pixlang/__private__/util/util__Environment.cmx" {"__private__/util/util__Environment.cmx"}
  "_build/install/default/lib/pixlang/__private__/util/util__Error_report.cmx" {"__private__/util/util__Error_report.cmx"}
  "_build/install/default/lib/pixlang/__private__/util/util__Position.cmx" {"__private__/util/util__Position.cmx"}
  "_build/install/default/lib/pixlang/dune-package"
  "_build/install/default/lib/pixlang/opam"
]
libexec: [
  "_build/install/default/lib/pixlang/__private__/analyser/analyser.cmxs" {"__private__/analyser/analyser.cmxs"}
  "_build/install/default/lib/pixlang/__private__/ast/ast.cmxs" {"__private__/ast/ast.cmxs"}
  "_build/install/default/lib/pixlang/__private__/interpreter/interpreter.cmxs" {"__private__/interpreter/interpreter.cmxs"}
  "_build/install/default/lib/pixlang/__private__/language_parser/language_parser.cmxs" {"__private__/language_parser/language_parser.cmxs"}
  "_build/install/default/lib/pixlang/__private__/util/util.cmxs" {"__private__/util/util.cmxs"}
]
bin: [
  "_build/install/default/bin/interpreter"
  "_build/install/default/bin/parser_visualiser"
]
doc: [
  "_build/install/default/doc/pixlang/README.md"
]
